# Generated by Django 5.0.8 on 2026-07-31 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('PUNTUAL', 'Puntual'), ('TOLERANCIA', 'Tolerancia'), ('RETARDO', 'Retardo'), ('FALTA', 'Falta'), ('JUSTIFICADO', 'Justificado'), ('DESCANSO', 'Descanso'), ('PERMISO', 'Permiso'), ('INCAPACIDAD', 'Incapacidad'), ('VACACIONES', 'Vacaciones'), ('OTRO', 'Otro')], max_length=20, null=True)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asistencias',
                'ordering': ['-date', 'employee__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empleados',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('device_date', models.DateField()),
                ('device_time', models.TimeField()),
                ('device_datetime', models.DateTimeField()),
                ('server_datetime', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('gps_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='attendance/employee/')),
                ('environment_photo', models.ImageField(blank=True, null=True, upload_to='attendance/environment/')),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.employee')),
            ],
            options={
                'db_table': 'registros_asistencia',
                'ordering': ['-device_datetime'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.employee'),
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification_type', models.CharField(choices=[('JUSTIFICADO', 'Justificado'), ('PERMISO', 'Permiso'), ('INCAPACIDAD', 'Incapacidad'), ('VACACIONES', 'Vacaciones'), ('DESCANSO', 'Descanso'), ('OTRO', 'Otro')], max_length=20)),
                ('reason', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='justifications/')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_justifications', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='attendance.attendance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='attendance.employee')),
            ],
            options={
                'db_table': 'justificaciones',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='attendance.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='attendance.workschedule')),
            ],
            options={
                'db_table': 'empleados_horarios',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('tolerance_minutes', models.PositiveSmallIntegerField(default=10)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='attendance.workschedule')),
            ],
            options={
                'db_table': 'horarios_dia',
                'ordering': ['weekday'],
                'unique_together': {('schedule', 'weekday')},
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workscheduleday'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
