# Generated by Django 5.0.8 on 2026-07-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role_type',
            field=models.CharField(choices=[('WORKER', 'Trabajador'), ('RH', 'RH')], default='WORKER', max_length=20),
        ),
    ]
